# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp Tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChatApp Tutorial

pod 'SwiftyJSON', '~> 4.0'
pod 'Alamofire', '~> 5.2'

pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'FirebaseFirestoreSwift'

pod 'Gallery'
pod 'RealmSwift'

pod 'ProgressHUD'
pod 'SKPhotoBrowser'

pod 'MessageKit'
pod 'InputBarAccessoryView'

pod 'IQKeyboardManagerSwift'
pod 'Localize-Swift', '~> 3.2'

pod 'RAMAnimatedTabBarController'

pod 'RxSwift'
pod 'RxCocoa'

pod 'KafkaRefresh'

end
